
data:
  target: dataset.data_module.BIRDataModule
  params:
    train_config: ./configs/dataset/c4d_train.yaml
    val_config: ./configs/dataset/c4d_val.yaml

model:
  config: ./configs/model/cldm_bsr_eval.yaml
  resume: ./weights/FlowIE_bsr_v1.pth

lightning:
  seed: 231
  trainer:
    accelerator: auto
    precision: 32
    devices: [0]
    default_root_dir: ./work_dirs/c4d_train
    max_steps: 50000
    val_check_interval: 400
    log_every_n_steps: 50
    accumulate_grad_batches: 4
    check_val_every_n_epoch: 1

  callbacks:
    - target: model.callbacks.ImageLogger
      params:
        log_every_n_steps: 250
        max_images_each_step: 4
        log_images_kwargs: ~

    - target: model.callbacks.ModelCheckpoint
      params:
        every_n_train_steps: 5000
        save_top_k: -1
        filename: {step}
