
data:
  target: dataset.data_module.BIRDataModule
  params:
    train_config: ./configs/dataset/c4d_train.yaml
    val_config: ./configs/dataset/c4d_val.yaml

model:
  config: ./configs/model/cldm_bsr_eval.yaml
  resume: ./weights/FlowIE_bsr_v1.pth

lightning:
  seed: 231
  trainer:
    accelerator: auto
    precision: 32
    devices: [0]
    default_root_dir: ./work_dirs/c4d_smoke_test
    max_steps: 12
    val_check_interval: 100
    limit_val_batches: 0
    log_every_n_steps: 2
    accumulate_grad_batches: 1
    num_sanity_val_steps: 0

  logger:
    target: pytorch_lightning.loggers.TensorBoardLogger
    params:
      save_dir: ./work_dirs/c4d_smoke_test
      name: tensorboard
      default_hp_metric: false

  callbacks:
    - target: model.callbacks.ImageLogger
      params:
        log_every_n_steps: 10
        max_images_each_step: 2
        log_images_kwargs: ~

    - target: model.callbacks.ModelCheckpoint
      params:
        every_n_train_steps: 10
        save_top_k: -1
        filename: step-{step}
